name: Running bot
 
on: push

env:
  TZ: America/Recife

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 525600

    steps:
       - name: Checkouts
         uses: actions/checkout@master
         
       - name: Initializing environments
         continue-on-error: true
         timeout-minutes: 100
         run: |
              git config --global user.name "VRB"
              git config --global user.email "secrets.EMAILGIT"
              mkdir tmp && cd tmp
              git clone ${{ secrets.REPOBASE }} VRB

       - name: Setup Velosh Node JS Bot
         continue-on-error: true
         timeout-minutes: 360
         run: |
              # Clone
              git clone https://github.com/Velosh/RequestBotJS.git VRBJS
              
              # Update and install npm/node and its deps
              sudo apt-get update -y
              sudo apt-get install nodejs-dev node-gyp libssl1.0-dev; sudo apt-get install expect npm -y
              
              # Now use sed to set vars
              cd VRBJS
              sed -i "s/token: ''/token: '${{ secrets.TOKEN }}'/g" config.js
              sed -i "s/mainChat: ''/mainChat: '${{ secrets.MAIN_CHAT }}'/g" config.js
              sed -i "s/privateChat: ''/privateChat: '${{ secrets.PRIVATE_CHAT }}'/g" config.js
              
              # Run bot
              npm i > /dev/null 2> /dev/null
              node . > /dev/null 2> /dev/null

       - name: Loop workflow
         continue-on-error: true
         timeout-minutes: 1
         run: |
              # CD to VRB repo (base) and do empty commit
              cd tmp/VRB
              git commit --allow-empty -m "(LOOP): Make a forced loop"
              
       - name: Reruns
         continue-on-error: true
         timeout-minutes: 5
         run: |
              cd tmp/VRB
              sudo apt-get install expect -y
              expect -c "
              spawn git push -f 
              expect \"Username\"
              send \"${{ secrets.USERNAME }}\r\"
              expect \"Password\"
              send \"${{ secrets.PASSWORD }}\r\"
              expect \"master -> master\"
              set timeout -10
              interact"
